import 'package:first_flutter/widgets/famous_module.dart';
import 'package:flutter/material.dart';

const Famous_module = const [
  Famous(
    id: 'f1',
    title: 'Attock',
    color: Colors.white24,
    image: 'assets/images/attock1.png',
    historical: [
      'Attock Fort',
      'Attock Khurd Railway Station',
      'Behram ki Baradari',
      'Gurdwara Panja Sahab',
      'Jand Public Park',
      'Lala Rukh Tomb and Hakeem Khan Tomb',
      'Maqbara-e-Lala Rukh ',
      'Shahpur DAM',
    ],
    cultural: ['Not Available'],
    religous: [
      'Dabar Sain Hazir Hazur',
      'Maira Sharif',
      'Gurdwara Panja Sahab',
    ],
  ),
  Famous(
    id: 'f2',
    title: 'Bahawalnagar',
    color: Colors.grey,
    image: 'assets/images/nagar1.png',
    historical: [
      'Fort Abbas Qila',
    ],
    cultural: ['Not Available'],
    religous: [
      'Dabar Hazrat Noor Muhammad Maharvi',
      'Dabar Hazrat Syed Fazal Hussain',
      'Dabar Hazrat Taj Ud Din Sarwar',
    ],
  ),
  Famous(
    id: 'f3',
    title: 'Bahawalpur',
    color: Colors.cyan,
    image: 'assets/images/bahawal.png',
    historical: [
      'Al- Sadiq Mosque',
      'Library',
      'Museum',
      'Darbar Mahal',
      'Dewara Fort',
      '	Farid Gate',
      'Gulzar Palace',
      'Mojgarh Fort',
      'Noor Mahal',
      'Purana Bangla',
      'Sadiq Dane High School',
      'Sadiq Garh Palace',
      'Shrine of Chanan Pir Bahawalpur',
      'Shrine of Prophet (PBUH) Companions Dewar',
      '	Abbasi Royal Graveyard Derawer Bahawalpur',
      'Tomb of Bibi Jawandi, Baha’al Halim and Ustaad and Tomb and Mosque of Jalal ud din Bukhari',
    ],
    cultural: [
      'Bhawalpur Library',
      'Bahawalpur Museum',
      'Noor Mahal',
      'TDCP Lal Sohanra Resort',
    ],
    religous: [
      'Abbasi Mosque',
      'Al- Sadiq Mosque',
      'Baba Shah Rangeela Shrine',
      'Darbar Jalal ud Din Surkh Bukari',
      'Darbar Khawaja Khuda Bakesh',
      'Mazrat uch-Sharif',
      'Shrine Kabir ud din',
      'Shrine of Chanan Pir Bahawalpur',
      'Shrine of Prophet (PBUH) Companions Dewar',
      'Tomb of Bibi Jawandi, Baha’al Halim and Ustaad and Tomb and Mosque of Jalal ud din Bukhari',
    ],
  ),
  Famous(
    id: 'f4',
    title: 'Bhakkar',
    color: Colors.lightBlue,
    image: 'assets/images/bhakkar.png',
    historical: [
      'Mankera Fort',
    ],
    cultural: ['Not Available'],
    religous: [
      'Shri Maha Veer ji Temple',
    ],
  ),
  Famous(
    id: 'f5',
    title: 'Chakwal',
    color: Colors.white54,
    image: 'assets/images/chakwal.png',
    historical: [
      'Chaukhadndi',
      'Fossil Museum',
      'Katas Raj Temples',
      'Malot Kot',
      'Malot Temple',
      'Minwal',
      'Ruiend Temple With Gateway',
      'Swaik Lake',
      'Takhat-e-Babri',
    ],
    cultural: [
      'Malot Temple',
      'TDCP kallar Kahar Resort',
    ],
    religous: [
      'Katas Raj Temples',
      'Malot Kot',
      'Malot Temple',
      'Saidan Shah Shrine',
      'Shrine of Saint Abdul Qadir Gilani Grandson',
    ],
  ),
  Famous(
    id: 'f5after',
    title: 'Chinot',
    color: Colors.white38,
    image: 'assets/images/mosque.png',
    historical: [
      'Shahi Mosque',
      'Umer Hayat Place or Gulzar Manzil',
    ],
    cultural: ['Umer Hayat Place or Gulzar Manzil'],
    religous: [
      'Shahi Mosque',
      'Dabar Hazrat Bu Ali Qalandir',
      'Dabar Pir Mohammad Siddique Lalian',
    ],
  ),
  Famous(
    id: 'f6',
    title: 'Dera Gazi Khan',
    color: Colors.greenAccent,
    image: 'assets/images/dg.png',
    historical: [
      'Jirga House',
      'Tomb of Gazi khan',
    ],
    cultural: [
      'Jirga House',
      'Tomb of Gazi khan',
      'TDCP Resort Fort Monroe',
      'TDCP Sakhi Resort',
    ],
    religous: [
      'Baba Pir Qatal',
      'Jammia Masjid',
      'Mahmoodia Tomb',
      'Sakhi Sarwar Shrine',
      'Shrine of Pir Adil',
      'Zinda pir',
      'Tomb Hazrat Khawaja Suleman',
    ],
  ),
  Famous(
    id: 'f7',
    title: 'Faisalabad',
    color: Colors.pinkAccent,
    image: 'assets/images/fasilabad.png',
    historical: [
      '	Faisalabad Clock Tower',
      'Faisalabad Railway Station',
      'Jinnah Park',
      'Lyallpur Museum',
    ],
    cultural: [
      'Chenab Club',
      'Faisalabad Clock Tower',
      'Faisalabad Railway Station',
      'Lyallpur Museum',
      'Qaisri Darwaza',
    ],
    religous: [
      'Temple Chak Jhumra',
    ],
  ),
  Famous(
    id: 'f8',
    title: 'Gujranwala',
    color: Colors.yellow,
    image: 'assets/images/gujar.png',
    historical: [
      'Chichraan Wala Mandir',
      'Darziyan Wali Kothi',
      'Eastcourt Clock Tower',
      'Lahori Gate and Sialkoti Gate',
      'Molana Zafar Ali Khan Shrine ',
      'Ranjit Singh Birthplace',
      'Saint Paul’s Presbyterian Church',
      'Samadhi of Atmaram',
      'Sheranwala Baradari',
      'Tomb of Maha Singh',
    ],
    cultural: ['Lahori Gate and Sialkoti Gate', 'Mukhtar King Fish'],
    religous: [
      'Chan Pir Shrine',
      'Gurdawara of Sikh',
      'Gurdawara Khara Sahib, Bhaike',
      'Gurdwara Rori Sahib Emnabad',
      'Molana Zafar Ali Khan Shrine',
      'Saint Paul’s Presbyterian Church',
    ],
  ),
  Famous(
    id: 'f9',
    title: 'Gujrat',
    color: Colors.teal,
    image: 'assets/images/gujrat.png',
    historical: [
      'Aziz Bhatti Shaheed Shrine',
    ],
    cultural: ['Not Available'],
    religous: [
      'Mohri Sharif Darbar',
      'Shah Daula Pir Shrine',
    ],
  ),
  Famous(
    id: 'f10',
    title: 'Hafizabad',
    color: Colors.orangeAccent,
    image: 'assets/images/hafiz.png',
    historical: ['Not Available'],
    cultural: ['Not Available'],
    religous: [
      'Mian Khair Mohammad Shrine',
      'Presbyterian Church Hafizabad',
    ],
  ),
  Famous(
    id: 'f11',
    title: 'Jhang',
    color: Colors.tealAccent,
    image: 'assets/images/jhang.png',
    historical: [
      'Heer Ranjha Darbar',
    ],
    cultural: [
      'Heer Ranjha Darbar',
    ],
    religous: [
      'Heer Ranjha Darbar',
      'Darbar Hazrat Amman Ullah Hathi Sarkar',
      'Dabar Hazrat Sultan Bahu',
      'Lal Nath Temple',
      'Maai Baap Darbar',
      'Maai Challan Wali Sarkar',
      'Shah Jewna Darbar',
    ],
  ),
  Famous(
    id: 'f12',
    title: 'Jhelum',
    color: Colors.limeAccent,
    image: 'assets/images/jhelum.png',
    historical: [
      'Alexander Monument',
      'Railway Station',
      'Khewra Salt Mine',
      'Masjid Afghana',
      'Rohtas Fort',
      'Tilla Jogian',
      'Tomb of Khair-un-Nisa',
    ],
    cultural: [
      'Khewra Salt Mine',
      'Shahab Ud Din Ghouri Shrine',
    ],
    religous: [
      'Bhai Karam Singh Gurdwara',
      'Gurdwara Chowa Sahib',
      'Jalalpur Sharif',
      'Khewra Salt Mine',
      'Masjid Afghana',
      'Shrine Ghulam Haider Shah',
      'St. John’s Church',
    ],
  ),
  Famous(
    id: 'f13',
    title: 'Kasur',
    color: Colors.lightBlue,
    image: 'assets/images/kasur.png',
    historical: [
      'Baba Buleh Shah Shrine',
      'Ganda Singh Wala Border',
      'Museum',
      'Tomp of Wakeel Khan',
    ],
    cultural: ['Not Available'],
    religous: [
      'Baba Buleh Shah Shrine',
      'Baba Shah Kamal Chisti Shrine',
    ],
  ),
  Famous(
    id: 'f14',
    title: 'Khanewal',
    color: Colors.lightBlueAccent,
    image: 'assets/images/khane1.png',
    historical: [
      '	Municipal Park & Jinnah Public library',
      'Railway Junction',
      'Tomb of Khalid Waleed',
    ],
    cultural: [
      'Jinnah Library',
      'Municipal Park & Jinnah Public library',
      'Tomb of Khalid Waleed'
    ],
    religous: [
      'Tomb of Khalid Waleed',
      'Abdul Hakeem Shrine',
      'Baba Mian Channu Shrine',
      'Kabir Bukhri Shrine',
      'Nasir Hussain Shah Shrine',
    ],
  ),
  Famous(
    id: 'f15',
    title: 'Khushab',
    color: Colors.grey,
    image: 'assets/images/khush.png',
    historical: [
      'Akrand Fort',
      'Amb Sharif',
      'Graveyard of Sahaba',
      'Nurshingh Phowar',
      'Ratrirri Ruins',
      'Sodhi Garden and Rest House',
      'Tulaijha Fort',
      'Tulhaath Fort',
    ],
    cultural: ['Angah', 'TDCP Khabeki Resort'],
    religous: [
      'Amb Sharif',
      'Dada Golra Shrine',
      'Daip Shareef',
      'Darbar Badshahan Khushab',
      'Graveyard of Sahaba',
      'Nurshingh of Sahaba',
      'Sakhi Sayed Al Maroof Shrine',
      'Sayedan Shah Bukhari Shrine',
    ],
  ),
  Famous(
    id: 'f16',
    title: 'Layyah',
    color: Colors.tealAccent,
    image: 'assets/images/layyah1.png',
    historical: [
      'Railway Station',
    ],
    cultural: ['Not Available'],
    religous: [
      'Darbar Jallo Shah',
      'Darbar Shah Habib',
      'Gaddu Lal Temple',
      'Mandir Shrine Cum Temple',
      'Rajan Shah Shrine',
    ],
  ),
  Famous(
    id: 'f17',
    title: 'Lodhran',
    color: Colors.greenAccent,
    image: 'assets/images/lodhran.png',
    historical: ['Not Available'],
    cultural: ['Not Available'],
    religous: [
      'Sultan Ayub Qatal Shrine',
    ],
  ),
  Famous(
    id: 'f18',
    title: 'Lahore',
    color: Colors.white,
    image: 'assets/images/lahore.png',
    historical: [
      'Akbar Sarai & Mosque',
      'Maryam Zamani Mosque',
      'Smadh of Bhai Wasti Ram',
      'Tomb of Qutab-ud-Din Aibak',
      '3rd Battalion 1965 War Monument',
      'Allama Iqbal Museum',
      'Badshahi Mosque',
      'Baradari and Samadh of Maharaja',
      'Chauburji',
      'Dai Anga Mosque',
      'Fortress Stadium Commercial Area',
      'Gates of Lahore & Waleed City',
      '	Ghulabi Bagh Gateway & Tomb of Dai Anga',
      'Haveli Nau-Nihal Singh',
      'Iqbal Tomb',
      'Islamic Summit Minar',
      'Jahangir Tomb',
      'Javed Manzil Lahore',
      'Kamran’s Baradari',
      'Kims Gun-Zamzama',
      'Budho Tomb',
      'Lahore Fort',
      'Heritage Museum, Tollinton',
      'Lahore Museum',
      'Railway Station',
      'Minar-e-Pakistan',
      'Mirza Kamran’s Baradari',
      'Punjab Public Library',
      'Quaid-e-Azam library, Lahore',
      'Samadhi of Sir Ganga Ram',
      'Samadhi Ranjit Singh',
      'Shahi Hamam',
      'Shalamar Bagh',
      'Sonehri Mosque',
      'Tomb of Ali Mardan',
      'Tomb of Anarkali',
      'Tomb of Asif khan',
      'Tomb of Dai Anga',
      '	Tomb of Nadra Begum',
      'Tomb of Nawab Bahadur Khan',
      'Tomb of Noor Jahan',
      'Tomb of Qutb-ud-din Aibak',
      'Tomb of zaib un nisa',
      'Wagah Border',
      'Wazir Khan Bardari',
      'Wazir Khan Hammam',
    ],
    cultural: [
      'Akbar Sarai & Mosque',
      'Abdur Rehman Chughtai Museum',
      'Allama Iqbal Museum',
      'Anarkali Bazar',
      'Eiffel Tower Lahore',
      'Food Street Lahore',
      'Fortress Stadium Commercial Area',
      'Gaddafi Stadium',
      'Islamic Summit Minar',
      'Lahore Heritage Museum, Tollinton',
      'Lord Bradlaugh Hall',
      'National Museum of Science and Technology',
      'Punjab Public Library',
      'Quaid-e-Azam Library',
      '	TDCP Sightseeing Lahore Bus Service',
    ],
    religous: [
      'Akbar Sarai & Mosque',
      'Badshahi Mosque',
      'Baba Sher Shah',
      'Bahria Town Mosque',
      'Cthedral Church',
      'Dai Anga Mosque',
      'Dabar Mian Mir',
      'Data Darbar',
      'Ghazi Ilmuddin Shaheed Mazar',
      'Gurdwara Dera Sahib',
      'Major Shahbir Sharif Shaeed',
      'Masjid Ibrahim',
      'Samadhi Ranjit Singh',
      'Sunehri Masjid Lahore',
      'Tomb of Ali Mardan',
      'Wazir Khan Hammam ',
      'Wazir Khan Mosque',
    ],
  ),
  Famous(
    id: 'f19',
    title: 'Mandi Bahaudin',
    color: Colors.cyanAccent,
    image: 'assets/images/mandi.png',
    historical: [
      'Cheelianwala Monument',
      'Qadirabad Fort',
    ],
    cultural: ['Not Available'],
    religous: [
      'Grudawara Bhai Bannu',
      'Grudawara Mandi Bahauddin',
    ],
  ),
  Famous(
    id: 'f20',
    title: 'Mian Wali',
    color: Colors.amber,
    image: 'assets/images/mian.png',
    historical: [
      'Ruins of Kafirkot',
    ],
    cultural: ['Not Available'],
    religous: [
      'Ruins of Kafirkot',
      'Sultan Muhammad Zakria Shrine',
    ],
  ),
  Famous(
    id: 'f21',
    title: 'Multan',
    color: Colors.white70,
    image: 'assets/images/multan.png',
    historical: [
      'Baha-ud-Din Zakria Shrine',
      'Multan Fort and Art Gallery',
      'Shah Rukn-e-Alam Shrine',
      'Shrine Shah Shamas Tabraiz',
      'Tomb of Shah Ali Akbar & his Mother',
    ],
    cultural: ['Multan Fort and Art Gallery'],
    religous: [
      'Baha-ud-Din Zakria Shrine',
      'Faqeer Fazal Shrine',
      'Shah Rukn-e-Alam Shrine',
      'Shahi Eid Gah Sharif',
      'Shrine Shah Shamas Tabraiz',
      'Tomb of Shah Ali Akbar & his Mother',
    ],
  ),
  Famous(
    id: 'f22',
    title: 'Muzaffargarh',
    color: Colors.yellowAccent,
    image: 'assets/images/muzaf.png',
    historical: [
      'Tomb of Tahir Khan Nahar',
    ],
    cultural: ['Not Available'],
    religous: [
      'Darbar Naukar Shah Ghazi',
      'Masjid Sakina Tus Sughra',
      'Muhid Shah Sakar',
    ],
  ),
  Famous(
    id: 'f23',
    title: 'Nankana Sahib',
    color: Colors.white60,
    image: 'assets/images/nankan.png',
    historical: [
      'Clock Tower Sangla hill',
      'Gurdwara Janam Asthan ',
      'Rai Bahadur',
    ],
    cultural: ['Not Available'],
    religous: [
      'Gurdwara Janam Asthan ',
      'Presbyerian Church Sangla',
      'TDCP Nakana Motel',
    ],
  ),
  Famous(
    id: 'f24',
    title: 'Narowal',
    color: Colors.orange,
    image: 'assets/images/hill1.png',
    historical: ['Not Available'],
    cultural: ['Not Available'],
    religous: [
      'Epiphany Church',
      'Gurdwara Darbar Sahib Kartarpur',
      'Kutab Shah Wali Shrine',
    ],
  ),
  Famous(
    id: 'f25',
    title: 'Okara',
    color: Colors.amberAccent,
    image: 'assets/images/okara1.png',
    historical: [
      'Bhuman Shah',
      'Depalpur Fort',
      'Mir Chakar Khan Rind Tomb',
    ],
    cultural: ['Mir Chakar Khan Rind Tomb'],
    religous: [
      'Bhuman Shah',
      'Darbar Hazrat Daud Bandgi',
      'Darbar Karman Wali Khan',
    ],
  ),
  Famous(
    id: 'f26',
    title: 'Pakpattan',
    color: Colors.cyanAccent,
    image: 'assets/images/pak.png',
    historical: [
      'Sikhon ki Marri',
    ],
    cultural: ['Masjid Waris Shah'],
    religous: [
      'Darbar Hazrat Baba Farid',
      'Masjid Waris Shah',
      'Milas Das',
      'Parnami Mandir',
      'Parnami Mandir, Malka Hans',
      'Sikhon ki Marri',
    ],
  ),
  Famous(
    id: 'f27',
    title: 'RahimYar Khan',
    color: Colors.white70,
    image: 'assets/images/yar.png',
    historical: [
      'Bhong Masjid',
      'Pattan Minara',
    ],
    cultural: ['Not Available'],
    religous: [
      '	Bhong Masjid',
    ],
  ),
  Famous(
    id: 'f28',
    title: 'Rawalpindi',
    color: Colors.grey,
    image: 'assets/images/rawal.png',
    historical: [
      'Dharma Rajika Stupa',
      'Farudgah-e-Shahan-e-Mughila Tank and Garden',
      'GPO Building',
      'Haveli Bheem Singh',
      'Julian',
      'Krishna Temple',
      'Loser Boali',
      'Mora Marudu',
      'Mughal Garden Wah',
      'Nicholoson Column',
      'Railway Station',
      'Rawalpindi Cricket Station ',
      'Sirkap',
      'Sirsukh',
      'Taxila Sites & Monuments',
    ],
    cultural: [
      'Mall Road Muree',
      'Municipal Library',
      'TDCP Khajot Stopover',
      'TDCP Patriata Chairlift & Cable Car system',
      'TDCP Restaurant Ghora Gali',
      'Taxila Sites & Monuments',
    ],
    religous: [
      'Archaeological Museum',
      'Balawara Sharif',
      'Dharma Rajika Stupa',
      'Hazrat Baba Pir Dhani Sarkar',
      'Julian',
      'Mankiala Stupa',
      'Panjpeer Rocks ',
      'Rawat Fort',
      'Roman Catholic Church',
      'Taxila Sites & Monuments',
      'The holy Trinity Church',
    ],
  ),
  Famous(
    id: 'f29',
    title: 'Rajanpur',
    color: Colors.blue,
    image: 'assets/images/tajan.png',
    historical: ['Not Available'],
    cultural: ['Khwaja Fareed Museum', 'TDCP Resort Kot Mithan'],
    religous: [
      'Hamza Sultan Shrine',
      'Hazrat Noor Mohammad Shrine',
      'Khawaja Gulam Fareed Shrine',
      'Peer Dhanu Shah',
      'Sahib Shah Darbar',
      'Sakhi Rindan',
      'Sakhi Shah Jahan Burkari',
    ],
  ),
  Famous(
    id: 'f30',
    title: 'Sheikhupura',
    color: Colors.blueAccent,
    image: 'assets/images/pura.png',
    historical: [
      'Sheikhupura Fort',
      'Pir Waris Shah Shrine',
      'Hiran Minar',
      'Sacha Sodha Gurdwara',
      'Baoli and Mosque',
      'TDCP Water',
      ' Sporits Hiran Minar',
    ],
    cultural: ['	Lahore Country Club'],
    religous: [
      'Sacha Sodha Gurdwara',
      'Pir Waris Shah Shrine',
      'Dabar Hazrat Sher Mohammad',
      'Noori Sarkar Mazar',
    ],
  ),
  Famous(
    id: 'f31',
    title: 'Sialkot',
    color: Colors.tealAccent,
    image: 'assets/images/sialkot3.png',
    historical: [
      '1965 War Monument',
      'Clock Tower',
      'Iqbal Manzil ',
      'Sialkot Fort',
    ],
    cultural: ['Iqbal Manzil', 'Murray College Sialkot'],
    religous: [
      '1.	Holy Trinity Church',
      'Imam Ali Haq Shrine',
      'Jubilee Church',
      'Kotli Bawa Faqeer Chand',
      'Up Church Chawinda',
    ],
  ),
  Famous(
    id: 'f32',
    title: 'Sahiwal',
    color: Colors.grey,
    image: 'assets/images/sahi.png',
    historical: [
      'Harrapa Archaeological Site & Museum',
    ],
    cultural: ['Not Available'],
    religous: [
      'Jamia Masjid Faridia',
    ],
  ),
  Famous(
    id: 'f33',
    title: 'Sargodha',
    color: Colors.green,
    image: 'assets/images/sargoda.png',
    historical: [
      'Arya Samaj Mandir',
      'Historical Gates of Sahiwal',
      'Jamia Masjid Bhera',
      'Largest Banyan Tree Kot Momin',
      'Sher Shah Suri Mosque',
      'Takht Hazara',
    ],
    cultural: ['Village Family Restaurant'],
    religous: [
      'Arya Samaj Mandir',
      'Jamia Masjid Bhera',
      'Sher Shah Suri Mosque',
    ],
  ),
  Famous(
    id: 'f34',
    title: 'Toba Tek Singh',
    color: Colors.white,
    image: 'assets/images/toba.png',
    historical: ['Not Available'],
    cultural: ['Not Available'],
    religous: [
      'Gurdwara Singhs Bha Gojra',
    ],
  ),
  Famous(
    id: 'f35',
    title: 'Vehari',
    color: Colors.white,
    image: 'assets/images/van.png',
    historical: ['Masood Jandhir Research Library'],
    cultural: ['Masood Jandhir Research Library'],
    religous: [
      'Baba Haji Sher Dewan',
      'Baba Jinday Shah',
      'Khawaja Abu Bakar Waraq',
    ],
  ),
];
